# -*- coding: utf-8 -*-
"""OOP base Banking System Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e0hp2rAJOWs0lsSqdouCX4zLAo2kHTm5

#***💰 Welcome to the Mini Banking System***
    A beginner-friendly Python project that simulates real-world banking features!

🏦 Create accounts, deposit funds, withdraw money, and check balances with            ease  all powered by OOP.

🧠 Perfect for learning core concepts while building something practical and   fun!
"""

#Bank operation using OOP

class Bank:
    bankname="State Bank of Pakistan"
    branch="Peshawar Saddar"

    #create account
    def __init__(self,username,pan,address):
        self.username=username
        self.pan=pan
        self.address=address
        self.balance=0.0 # set account balance to 0.0
        print(f'Hello {self.username} cong! your account craeted successfully ')

    #depoist
    def deposit(self,amount):
        self.balance=self.balance+amount
        print(f'{amount} deposited successfully')

    #withdraw
    def withdraw(self,amount):
        if amount<self.balance:
            self.balance=self.balance-amount
            print(f'{amount} withdraw successfully')
        else:
            print('Insufficent Fund...')

    #ministatement
    def ministatement(self):
        print(f'Your current account balance is {self.balance}')


print(f'Welcome to {Bank.bankname} , {Bank.branch}')
#collect user data for account creation
username=input('Enter Your name :')
pan=input('Enter PAN card number : ')
address=input('Enter Your address : ')

b=Bank(username,pan,address) # object creation based on user provided data

while True:
    print('\nPlease Select any Option : ')
    print('1.Deposit\n2.Withdraw\n3.Ministatement\n4.Stop')
    option=int(input(' '))

    if option==1:
        amount=float(input('Enter Deposited amount : '))
        b.deposit(amount)

    elif option==2:
        amount=float(input('Enter Withdraw amount : '))
        b.withdraw(amount)

    elif option==3:
        b.ministatement()

    elif option==4:
        print('Thanks for using State Bank of Pakistan .... ')
        break
    else:
        print('Invalid Option plz select a  valid option')